blueprint:
  name: Awtrix Set App Time
  description: Set the app time of the Ulanzi Clock
  domain: automation
  author: Smart Home Junkie
  input:
    awtrix_display:
      name: Awtrix Display
      description: Select the target Awtrix display.
      selector:
        device:
          model: "AWTRIX Light"
    apptime_helper:
      name: App Time Number Helper
      description: Select the App Time Number Helper that stores the App time.
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input apptime_helper

variables:
  device_id: !input awtrix_display
  my_display: >
    {{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name') ) }}
  apptime_value: !input apptime_helper

action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{my_display}}/settings"
      payload: |-
        {   
          "ATIME": "{{ states(apptime_value) }}"
        }
