blueprint:
  name: Awtrix Toggle Stock App
  description: Toggle a stock app on the Ulanzi Clock
  domain: automation
  author: Smart Home Junkie
  input:
    awtrix_display:
      name: Awtrix Display
      description: Select the target Awtrix display.
      selector:
        device:
          model: "AWTRIX Light"
    toggle_helper:
      name: Toggle Helper
      description: Select the Toggle Helper that will toggle the App on or off.
      selector:
        entity:
          domain: input_boolean
    stock_app:
      name: Sensor
      description: Select the stock app that you'd like to toggle.
      selector:
        select:
          options:
            - label: "Time"
              value: "time"
            - label: "Date"
              value: "date"
            - label: "Temperature"
              value: "temp"
            - label: "Humidity"
              value: "hum"
            - label: "Battery"
              value: "bat"

trigger:
  - platform: state
    entity_id: !input toggle_helper
    to: "on"
    id: "On"
  - platform: state
    entity_id: !input toggle_helper
    to: "off"
    id: "Off"

variables:
  device_id: !input awtrix_display
  my_display: >
    {{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name') ) }}
  stock_app: !input stock_app
  my_toggle_helper: toggle_helper

action:
  - if:
      - condition: trigger
        id: "On"
    then:
      - service: mqtt.publish
        data:
          qos: 0
          retain: false
          topic: "{{my_display}}/apps"
          payload: '[  {    "name": "{{stock_app}}",    "show": true  }]'
    else:
      - service: mqtt.publish
        data:
          qos: 0
          retain: false
          topic: "{{my_display}}/apps"
          payload: '[  {    "name": "{{stock_app}}",    "show": false  }]'
